In [44]:
import pandas as pd
import numpy as np
pd.set_option("display.max_rows",200)

In [3]:
dataset = pd.read_csv(r"D:\data science projecta\groceries - groceries.csv")

In [7]:
dataset.head(3)

,Item(s),Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,...,Item 23,Item 24,Item 25,Item 26,Item 27,Item 28,Item 29,Item 30,Item 31,Item 32
0,4,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
dataset["Item 1"][0]

'citrus fruit'

In [10]:
dataset.shape

(9835, 33)

In [12]:
market=[]
for i in range(0,dataset.shape[0]):
    cus=[]
    for j in dataset.columns :
        if type(dataset[j][i])==str:
            cus.append(dataset[j][i])
    market.append(cus)

In [80]:
market[:10]

[['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['whole milk'],
 ['pip fruit', 'yogurt', 'cream cheese', 'meat spreads'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['rolls/buns'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['potted plants'],
 ['whole milk', 'cereals']]

In [26]:
l=[]
for i in market:
    for j in i :
        l.append(j)

In [79]:
l[:10]

['citrus fruit',
 'semi-finished bread',
 'margarine',
 'ready soups',
 'tropical fruit',
 'yogurt',
 'coffee',
 'whole milk',
 'pip fruit',
 'yogurt']

In [18]:
import collections

In [38]:
p = collections.Counter(l)

In [39]:
d = {"Item Name":p.keys(),"values":p.values()}

In [78]:
pd.DataFrame(d).sort_values(by=["values"],ascending=False).head(10)

           Item Name  values
7         whole milk    2513
11  other vegetables    1903
17        rolls/buns    1809
31              soda    1715
5             yogurt    1372
24     bottled water    1087
42   root vegetables    1072
4     tropical fruit    1032
52     shopping bags     969
50           sausage     924

In [46]:
from mlxtend.preprocessing.transactionencoder import TransactionEncoder

In [48]:
tr = TransactionEncoder()
tr.fit(market)

C:\Users\nk\anaconda3\Lib\site-packages\sklearn\externals\_numpydoc\docscrape.py:383: UserWarning: potentially wrong underline length...
Parameters
------------ in
Encoder class for transaction data in Python lists
...
  if not self._is_at_section():
C:\Users\nk\anaconda3\Lib\site-packages\sklearn\externals\_numpydoc\docscrape.py:203: UserWarning: potentially wrong underline length...
Attributes
------------ in
Encoder class for transaction data in Python lists
...
  while not self._is_at_section() and not self._doc.eof():
C:\Users\nk\anaconda3\Lib\site-packages\sklearn\externals\_numpydoc\docscrape.py:203: UserWarning: potentially wrong underline length...
Examples
------------ in
Encoder class for transaction data in Python lists
...
  while not self._is_at_section() and not self._doc.eof():

TransactionEncoder()

In [57]:
df = pd.DataFrame(tr.transform(market),columns=tr.columns_)

In [61]:
from mlxtend.frequent_patterns import apriori

In [77]:
apriori(df, min_support=0.05,use_colnames=True,max_len=3).sort_values(by=["support"]).head(10)

     support                             itemsets
13  0.052364                 frozenset({napkins})
0   0.052466                    frozenset({beef})
8   0.053279                    frozenset({curd})
4   0.055414                  frozenset({butter})
30  0.056024      frozenset({yogurt, whole milk})
29  0.056634  frozenset({rolls/buns, whole milk})
18  0.057651                    frozenset({pork})
7   0.058058                  frozenset({coffee})
12  0.058566               frozenset({margarine})
10  0.058973             frozenset({frankfurter})

In [69]:
from mlxtend.frequent_patterns import fpgrowth

In [76]:
fpgrowth(df,min_support=0.05,use_colnames=True,max_len=3).sort_values(by=["support"]).head(10)

     support                             itemsets
24  0.052364                 frozenset({napkins})
13  0.052466                    frozenset({beef})
12  0.053279                    frozenset({curd})
8   0.055414                  frozenset({butter})
28  0.056024      frozenset({yogurt, whole milk})
30  0.056634  frozenset({rolls/buns, whole milk})
26  0.057651                    frozenset({pork})
4   0.058058                  frozenset({coffee})
1   0.058566               frozenset({margarine})
15  0.058973             frozenset({frankfurter})